apiVersion: v1
kind: Service
metadata:
  name: reddit-clone-service
  labels:
    app: reddit-clone
spec:
  selector:
    app: reddit-clone
  ports:
    - name: http
      protocol: TCP
      port: 30000
      targetPort: 30000
  type: ClusterIP
